### ISSUE TITLE
two message OwO response is pretty annoying - Make it one message instead?

### ISSUE THREAD

**Issue by SierraNB** [oct2pus/jadebot#8]
Jadebot will send a  message containing "oh woah what's this" and then another message containing an emoji. for a total of two messages

Please make it _one_ message so it doesn't fill up chat as much.

**Comment by oct2pus** [comment]
this is way late, I apologize.

This was an intentional decision to force larger emoji sizes, since (at the time?) in-line emojis were pretty small. Most phrases this is probably less annoying since you they activate significantly less but triggers on any occurance of 'owo'. E.G. A Scunthorpe Problem, but I left that in as an intentional feature since it mildly amused me.

I do want to do some sprucing up of the codebase, I'll consider changing it when I do so.
